### ISSUE TITLE
error messag when invalid credentials ui/ux design is acceptable

### ISSUE THREAD

**Issue by aryan-basu** [aryan-basu/Pclub-Meet#19]

**Comment by aryan-basu** [comment]
yes you can idk weather my project is yet registered for hackoctober or not
but you can do it if you want... make sure it looks better with the theme
if it  looks good we will merge it

**Comment by imakish** [comment]
I have made a pull request, please check if that is what you wanted.

**Comment by aryan-basu** [comment]
can you add screenshot or separate branch ?

**Comment by aryan-basu** [comment]
@imakish is my project is showing in your progress of hackoctober? i want to confirm is my project is registered or not

**Comment by akishtp** [comment]
@aryan-basu Yes, It is registered and is counting towards my contributions.
